### ISSUE TITLE
tests: Use fuzz testing

### ISSUE THREAD

**Issue by rdimitrov** [rdimitrov/go-tuf-metadata#12]

**Comment by MDr164** [comment]
Are there any requirements as to how the fuzz tests are to be executed? E.g. should there be a nightly run on GitHub action runners or is a more elaborate setup with services like OSS-Fuzz planned? And lastly, how should we deal with the seed corpus? Should the run be capped to e.g. an hour runtime and then export the corpus for later runs or should an ephemeral corpus be generated every time that is only kept during any single run?

**Comment by rdimitrov** [comment]
Frankly speaking I don't have a lot of experience in fuzz testing so you will be more than welcome to suggest what fits where and what would be the right approach for doing that. My intentions behind this were to start by exploring whether fuzzing fits the use case of the project. That said, it will be awesome if you're willing to help with this! 💯

**Comment by MDr164** [comment]
Well it's always good to fuzz test anything that can get arbitrary user input. Be it the root bytes, the repo URL, cache paths etc. The 'issue' with OSS-Fuzz is that you first need to apply for acceptance so you can run those tests on their GCP infrastructure continuously. In fuzzing you'll have to seed the input which will then be mutated. If a certain mutation reaches a new branch of execution the seed corpus will be adapted so the mutation of input is guided based on existing findings. Golangs fuzz testing support also allows exporting the generated corpus so you can basically start off where you stopped last time. If we just provide an initial corpus it will start a different path of mutation so technically it could also find good results without re-using the generated corpus of previous runs. In that case every run will create a new ephemeral corpus which will only live for the runtime of the running test. The later will be rather easy to implement. I can create a GitHub action job that runs nightly for an hour or so and just fuzzes all the targets with the same basic seed corpus per target.

**Comment by rdimitrov** [comment]
Thanks for the clarification! 💯 

I'm thinking if the free tier of Github Action minutes would suffice these types of tests? 

Nevertheless, let's see how it goes and in case it's quite resourceful we can comment/limit it until we move this to the go-tuf repo where there should be more Github Actions resources.

**Comment by MDr164** [comment]
To quote the billing page:
> GitHub Actions usage is free for standard GitHub-hosted runners in public repositories
And as this repo is public there should be no issue to run the fuzz test for about 30 minutes every night.

**Comment by rdimitrov** [comment]
That's nice to hear! 👍 Not sure why I remember it was limited to some extend

**Comment by MDr164** [comment]
It is limited on private repos to 2000 minutes per account afaik in the free tier. In general private repos are always under a CI quota. And we are limited to the smallest runner here but that should not really limit the fuzzing to much memory wise.

**Comment by rdimitrov** [comment]
Aah, you're right! I've started the project as a private one until it matured so that explains my confusion 😃

**Comment by rdimitrov** [comment]
Closing in favour of https://github.com/theupdateframework/go-tuf/issues/177
