### ISSUE TITLE
tests: Add unit tests for Updater

### ISSUE THREAD

**Issue by rdimitrov** [rdimitrov/go-tuf-metadata#16]

**Comment by rdimitrov** [comment]
I think @ivanayov had something started on that, let's see if she's ready to submit her effort so you use it as a base the least 👍

**Comment by MDr164** [comment]
Ah good to know. I'll wait then an unassign myself for the time being. :+1:

**Comment by ivanayov** [comment]
Hi @MDr164 ,

I added nearly 65% updater test coverage in #65 .

Feel free to add more.
This mainly covers top level update and consistent snapshot tests. 
They follow the python-tuf approach, so the [python-tuf tests](https://github.com/theupdateframework/python-tuf/tree/develop/tests) could be used for reference.
 What's still missing is key rotations, fetch targets and delegation graphs tests.
