### ISSUE TITLE
bug: use the correct format for "expires" (should not include milliseconds)

### ISSUE THREAD

**Issue by rdimitrov** [rdimitrov/go-tuf-metadata#22]

**Comment by jku** [comment]
The way I've read the spec is that fractions are not allowed and IIRC python-tuf API strips them out when expiry is set and does not accept fractions when deserializing JSON (but I could be wrong on the last bit)

**Comment by rdimitrov** [comment]
Thanks! Apparently we have to update the way we format and store this then 👍 

I checked root-signing and I see that at some point go-tuf was generating metadata like that - 

https://github.com/sigstore/root-signing/blob/ca9c5644c3217886b543265bacea774351bc0bde/repository/repository/1.root.json#L27C3-L27C3 

but eventually it switched to - 

https://github.com/sigstore/root-signing/blob/ca9c5644c3217886b543265bacea774351bc0bde/repository/repository/root.json#L6.

I'll update the issue's title so we can track this fix here 👍

**Comment by rdimitrov** [comment]
closing in favour of https://github.com/theupdateframework/go-tuf/issues/596
