### ISSUE TITLE
feat: Add support for listing available target files

### ISSUE THREAD

**Issue by rdimitrov** [rdimitrov/go-tuf-metadata#23]
As discussed in go-tuf, something like - 

> e.g. `tuf-client list` prints top-level targets
`tuf-client list <delegation>` prints targets for delegation

**Comment by rdimitrov** [comment]
This has been partially added by having the `GetTopLevelTargets()` methods for both updater and multirepo clients (i.e. [updater](https://github.com/rdimitrov/go-tuf-metadata/blob/7bcead451b5fdef252b5c9315bdbc562a0ec936c/metadata/updater/updater.go#L572))

**Comment by jku** [comment]
> This has been partially added by having the `GetTopLevelTargets()` methods for both updater and multirepo clients

This sounds like a reasonable way to reach parity with legacy go-tuf...

I have written a bit about the issues with generic target lookup in the python-tuf issue: https://github.com/theupdateframework/python-tuf/issues/1995 -- it's not trivial to do this for generic TUF repositories while not making new security holes: see especially https://github.com/theupdateframework/python-tuf/issues/1995#issuecomment-1335190904
