### ISSUE TITLE
feat: Make logging in library code optional

### ISSUE THREAD

**Issue by MDr164** [rdimitrov/go-tuf-metadata#57]
### Is your feature request related to a problem? Please describe.

As of today we still pull in logrus inside library code which will then require every user of the library to pull in the same logger. This creates unnecessary dependencies for consumers of the library portion of this repo.

### Describe the solution you'd like

Make logging optional for library code and/or remove the dependency on an external logger. The cleanest way would be to follow OpenTelemetrys strategy to use [logr](https://github.com/go-logr/logr) which is merely an interface for any supported logger that can be plugged into the codebase. It supports structured logging, loglevels and most importantly if no logger is supplied also supports a no-op fallback. This would also allow to continue using logrus for non-library code as logrus can be used with this interface. Work is also under way to support the new `slog` package of Go inside logr.

### Additional context

This issue was discussed prior on the CNCF Slack, the consensus was to make logging optional and more flexible as there is no hard dependency on logrus.

**Comment by rdimitrov** [comment]
Thanks for this enhancement! 💯 

We already discussed it on Slack but I'm definitely supportive of this, especially that if no logger is used it defaults to noop.

**Comment by MDr164** [comment]
I was unsure if I can modify the function signatures so instead of passing a logger into each function that has debug logging capabilities I opted for a package global logger with a getter and setter. Let me know if you have any preference over one or the other. As of right now the default is to log to os.Stdout but I can change the default to logr.Discard() which will not log anything. The benefit of using a package global logger instance is that in a normal programm flow one can plug in their custom logger like logrus and it just propagates to all the library functions. But if having a package global logger is a security concern (all it could do is intercept logs) I would have to adapt the functions to take a logger interface explicitly or a context.Context to which a logger can be attached.

**Comment by rdimitrov** [comment]
Thank you for the summary!

I was thinking for a while if we should avoid having a logger at all (for the library) and leave this decision to its users, but debugging TUF sometimes can be difficult and having these debug messages sure is handy. Your proposed changes are nice and does help resolve any "discomfort" caused by this. 

> I was unsure if I can modify the function signatures so instead of passing a logger into each function that has debug logging capabilities I opted for a package global logger with a getter and setter in https://github.com/rdimitrov/go-tuf-metadata/pull/58.

Changing the API layout might be a bit too intrusive, so having a global logger is the better option 👍 

> But if having a package global logger is a security concern (all it could do is intercept logs) I would have to adapt the functions to take a logger interface explicitly or a context.Context to which a logger can be attached.

There isn't anything secret that we log, like private keys and such, so it shouldn't be a problem 👍 

One thing I noticed now is there's logs in the tests too. Let me know what you think, but I don't think there's a lot of value in that so we should be able to safely discard them.

Overall it looks great! Thanks for tackling with this 👍

**Comment by MDr164** [comment]
I'd also say adding items to the function signatures should not be necessary and as you said the logger does not log anything sensitive. I'll polish the PR and convert it from a draft into a regular PR afterwards. For the logging in tests I'd propose to make the tests in general a bit more idiomatic. The majority is already fine but we can use the `testing.T` object more to control logging directly via the builtin `go test` tool and won't have to include any custom logging into the tests at all. But this PR is already quite large so I would create a separate follow-up PR for the tests. I'll try to make the PR as unintrusive to the existing tests as possible.
